Repository magpylib/magpylib, pull requests merged in 2022-04, with the labels that each got.

#508 fix tiling in `getBH`
  magpylib/_src/fields/field_wrap_BH_level2.py
  tests/test_getBH_level2.py
Labels: bug

#510 Catch `Collection` self referencing
  magpylib/_src/obj_classes/class_Collection.py
  tests/test_obj_Collection_child_parent.py
Labels: bug

#522 Pyvista dependencies
  .binder/apt.txt
  .binder/start
  .readthedocs.yaml
  docs/conf.py
  docs/examples/examples_30_coil_field_lines.md
Labels: docs, graphics

#524 Plotly plotting performance
  magpylib/_src/display/plotly/plotly_display.py
Labels: performance, graphics

#525 🚀 4.0.1 release
  CHANGELOG.md
  magpylib/__init__.py
  setup.py
Labels: performance, graphics
